AWSTemplateFormatVersion: 2010-09-09

Description: This CloudFormation template creates an S3 bucket.

Parameters:
  S3BucketName:
    Description: The name of the S3 Bucket to create
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  S3BucketArn:
    Description: the ARN of the S3 bucket.
    Value: !GetAtt S3Bucket.Arn
