AWSTemplateFormatVersion: 2010-09-09

Description: >
  This CloudFormation template sets up an RDS event subscription to send notifications to an SNS topic when specific database events occur. 
  The user can provide a list of instances to subscribe to, and the subscription is configured to send notifications for some event categories. 
  These categories include failover, failure, low storage, maintenance, etc.

Parameters:
  DbAlarmTopic:
    Description: The database alarm topic
    Type: String

  SourceInstances:
    Type: CommaDelimitedList
    Description: Instances that event subscription will consume events from.
    ConstraintDescription: If multiple values are passed they must be a list of strings separated by commas for example => instance-1, instance-2

Resources:
  DbEventSubscription:
    Type: AWS::RDS::EventSubscription
    Properties:
      SnsTopicArn: !Ref DbAlarmTopic
      SourceType: db-instance
      SourceIds: !Ref SourceInstances
      EventCategories:
        - failover
        - failure
        - low storage
        - maintenance
        - notification
        - recovery
      Enabled: true
